name: Auto Mention on Issue

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened,reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  mention:
    runs-on: ubuntu-latest
    steps:
    - name: issue mention user
      if: github.event_name == 'issues'
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          @richerfu Please check this issue, thanks.

    - name: pr mention user
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          @richerfu Please check this PR, thanks.
